name: 03 Env and Secrets
on:
  workflow_dispatch:
    inputs:
       environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  
env:
  DEV_URL: 'https://docs.github.com/en/developers'
  UAT_URL: 'https://uat.github.com'
  PROD_URL: 'https://uat.github.com'

jobs:
  use-env-dev:
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: ${{ env.DEV_URL}}
      
    steps:
         - run: echo " Run id = ${{ github.run_id }} "
         
         - run: echo " Deployment to ${{ env.DEV_URL }} "
         
         - name: echo env secret is redacted in logs
           run: |
            echo env secret is ${{ secrets.MY_ENV_SECRET }}
            echo ${{ secrets.MY_ENV_SECRET}} | sed 's/./&/g'
