name: 02-2 Greet Everyone

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'What is your name'
        required: true
        default: 'Skyehus Team'

jobs:
  greet-users:
    name: Greeting
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:  
          who-to-greet: "${{ github.event.input.name }} ${{ inputs.name}}"
        id: hello

      - name: Echo the time when it is greeted
        run: echo " time was ${{ steps.hello.outputs.time }}"
      
